version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.15.0
    container_name: veritas-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage
      - QDRANT__SERVICE__ENABLE_CORS=true
      - QDRANT__CLUSTER__ENABLED=false
      - QDRANT__SERVICE__MAX_REQUEST_SIZE_MB=32
    volumes:
      - qdrant_storage:/qdrant/storage
      - ./docker/qdrant/config:/qdrant/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - veritas-network

  qdrant-dashboard:
    image: qdrant/qdrant:v1.15.0
    container_name: veritas-qdrant-dashboard
    ports:
      - "6335:6333"
    depends_on:
      qdrant:
        condition: service_healthy
    command: ["./qdrant", "--uri", "http://qdrant:6333"]
    profiles: ["dashboard"]
    networks:
      - veritas-network

volumes:
  qdrant_storage:
    driver: local

networks:
  veritas-network:
    driver: bridge
